### ISSUE TITLE
英国视频无法播放

### ISSUE THREAD

**Issue by chantisnake** [xiaoyaocz/BiliBili-UWP#10]
播放视频的时候会卡在缓冲视频这里
![capture](https://cloud.githubusercontent.com/assets/10100995/21072328/1e48a9b0-beb6-11e6-991f-2ea49f8af56c.PNG)

重启电脑，重装 app 均无效，所有视频都无法播放，其他同学的也这样

**Comment by ThomasWFan** [comment]
非常抱歉，这个Bug需要一阵子才可以被修复；Bilibili更新了API

**Comment by chantisnake** [comment]
fixed，谢谢

**Comment by ThomasWFan** [comment]
商店审核稍微久了点，再加上另一开发者橙子那暴脾气。。所以稍微慢了点，抱歉。
