### ISSUE TITLE
请问可以上传最新代码吗

### ISSUE THREAD

**Issue by DaweiX** [xiaoyaocz/BiliBili-UWP#12]
如题，开发者幸苦了

**Comment by ThomasWFan** [comment]
由于我俩都没空，所以BilibiliUWP暂停维护。。。一段时间。等农历开年了我们考虑恢复维护。对造成的不便表示抱歉。

**Comment by DaweiX** [comment]
那请问现在2.7.8的代码方便上传吗？幸苦了。另外，如果需要的话，我也可以参与改进这个app。

发送自我的 Windows 10 手机

发件人: ThomasWFan<mailto:notifications@github.com>
发送时间: 2017年1月11日 11:14
收件人: xiaoyaocz/BiliBili-UWP<mailto:BiliBili-UWP@noreply.github.com>
抄送: DaweiX<mailto:DaweiX@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [xiaoyaocz/BiliBili-UWP] 请问可以上传最新代码吗 (#12)


由于我俩都没空，所以BilibiliUWP暂停维护。。。一段时间。等农历开年了我们考虑恢复维护。对造成的不便表示抱歉。

―
