### ISSUE TITLE
伪装成大陆用户出错

### ISSUE THREAD

**Issue by chantisnake** [xiaoyaocz/BiliBili-UWP#7]
获得 代理读取信息失败，请重试 提示框

之后下方出现错误：
Error reading JObject from JsonReader.Path '', line 0

**Comment by ThomasWFan** [comment]
您好，由于我们的服务器还处于测试期，所以经常会更换地址、关机维护或出现玄学故障。我们会尝试提供更好的服务器以增进该功能体验。感谢关注BilibiliUWP。另：由于Github并非我们的工作Git，我们仅仅用它来开放代码而已，所以代码更新会晚一些。

**Comment by ThomasWFan** [comment]
经测试，改Bug已经修复。感谢您的反馈
